### PR TITLE
reset the error handler before throwing a GDALError

### LINKED ISSUE #68: error handler not properly reset
Below example shows that `getdriverbyname` for non supported drivers returns null and doesn't throw. So far so good, this is apparently GDAL behavior since it is wrapped in `failsafe`. Calling `getdrivershortname` on this non existent driver does throw an error, fine. But then when I go back to `getdriverbyname` it does throw. Seems like while handling the GDAL error in error.jl, we don't properly reset the error state.

```julia
julia> using GDAL

julia> GDAL.allregister()

julia> driver = GDAL.getdriverbyname("ECW")
Ptr{GDAL.GDALDriverH} @0x0000000000000000

julia> driver = GDAL.getdriverbyname("ECW")
Ptr{GDAL.GDALDriverH} @0x0000000000000000

julia> driver = GDAL.getdriverbyname("NetCDF")
Ptr{GDAL.GDALDriverH} @0x0000000000000000

julia> GDAL.getdrivershortname(driver)
ERROR: GDALError (CE_Failure, code 10):
        Pointer 'hDriver' is NULL in 'GDALGetDriverShortName'.


Stacktrace:
 [1] gdaljl_errorhandler(::GDAL.CPLErr, ::Int32, ::Cstring) at C:\Users\visser_mn\.julia\dev\GDAL\src\error.jl:26
 [2] getdrivershortname(::Ptr{GDAL.GDALDriverH}) at C:\Users\visser_mn\.julia\dev\GDAL\src\gdal_h.jl:538
 [3] top-level scope at none:0

julia> driver = GDAL.getdriverbyname("NetCDF")
ERROR: GDALError (CE_Failure, code 10):
        Pointer 'hDriver' is NULL in 'GDALGetDriverShortName'.


Stacktrace:
 [1] failsafe(::Ptr{GDAL.GDALDriverH}) at C:\Users\visser_mn\.julia\dev\GDAL\src\error.jl:34
 [2] getdriverbyname(::String) at C:\Users\visser_mn\.julia\dev\GDAL\src\gdal_h.jl:398
 [3] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by visr**
Fixes #68. This means we cannot use `cplgetlasterror`* functions after an error anymore, but we can just get this information from the GDALError struct, as shown in the tests.

It seems quite neccesary to me to do this, since otherwise you get old error reports back, any time you call a new function that calls `failsafe` to check for errors, as shown in the issue.

Also expands and concentrates the error testing code.

### CODE REVIEW

File: src/error.jl [hunk 1]
```diff
@@ -23,7 +24,9 @@ function gdaljl_errorhandler(class::CPLErr, errno::Cint, errmsg::Cstring)
     # function signature needs to match the one in __init__, and the signature
     # of the callback for a custom error handler in the GDAL docs
     if class in throw_class
-        throw(GDALError(class, errno, unsafe_string(errmsg)))
+        msg = unsafe_string(errmsg)
+        cplerrorreset()
```
Comment (evetion) [inline src/error.jl]: You call `cplerrorreset` twice now, one here, one in the `GDALError`.

Comment (visr) [reply src/error.jl]: That is a different path though. That is in the 0 arg constructor, which this one doesn't use.
