### PR TITLE
return nothing for NULL strings

### LINKED ISSUE #67: getattrvalue can be avoid throw expection and more julia way
`function getattrvalue(hSRS::Ref{OGRSpatialReferenceH}, pszName, iChild::Integer) `

return unsafe_string directly, if the result ccall returned is NULL, unsafe_string throw exception:

`ERROR: ArgumentError: cannot convert NULL to string`

call getattrvalue function need to handle exception,not easy to use.

I think getattrvalue function can add a judgment when returning, avoid to throw exception:
```
function getattrvalue(hSRS::Ref{OGRSpatialReferenceH}, pszName, iChild::Integer)
    result = ccall((:OSRGetAttrValue, libgdal), Cstring, (Ptr{Cvoid}, Cstring, Cint), hSRS, pszName, iChild)
    result != Cstring(Ptr{UInt8}(0)) ? unsafe_string(result) : nothing
end
```
I can call getattrvalue function by this way:
```
if getattrvalue(...) != nothing
...
else
...
end
```
or
`getattrvalue(...) != nothing && ...`

Instead of handling exceptions, do you think so ?

### PR DESCRIPTION
**Pull request by visr**
Fixes #67.

Currently this errors with `ArgumentError: cannot convert NULL to string` in `unsafe_string`, even though many functions are documented to return NULL in certain cases, that are not errors. This now works similarly to many Base functions like `findfirst`, that return `nothing` in case nothing is found.

### CODE REVIEW

**Comment by visr** [comment]
Thanks, your comments made me think about this again, and try something different. First my replies to your points:

> Is the name unsafe_string_or_nothing better?

From the `unsafe_string` docs: "This function is labeled "unsafe" because it will crash if p is not a valid memory address to data of the requested length." In this case I wouldn't call it unsafe since we know that GDAL allocated this memory.

> Maybe we could document this change somewhere?

Yeah, I think we just need to make a changelog for going from v0.2 to v1.0. I'd prefer at this point to do that all at once I think. (Going forward we should keep it up to date)

> You could also return an empty string for example, as that is at least the same type.

Yeah but then you cannot distinguish it from an actual empty string result. And since this method is used by Base as well it seems like a better choice.

> Does the C_NULL indicate different things for different function (i.e. an error or nothing)?

It seems like it, from the docs:

- CPLSerializeXMLTree: the document on success or NULL on failure.
- VSIGetFileSystemOptions: a string, which must not be freed, or NULL if no options is declared.


Especially the last point made me think, currently we only check for errors when we get a `Ptr{Cvoid}` back from GDAL that is a NULL pointer. Digging back a little, to Even Rouault's comment in https://github.com/JuliaGeo/GDAL.jl/issues/19#issuecomment-238096271:

> CPLError() can be called whether the return code of the function is successful or not, but I'd suggest that you can check with CPLGetLastErrorXXXX() when the return code is an error (or if you check always, do not error out if the error type was just a warning for example)

So the new commit here effectively switches to always checking for errors, but only throwing on `CE_Failure`. I took out `CE_Fatal` from the error checking codes since this is not in need of checking anyway, if this happens, it also crashes julia, just try running `GDAL.cplemergencyerror("things are bad")` if you can lose your julia session.

This also introduces a list of functions that return Cstring and are known to need their memory freed. For now I only put in `gdalinfo`. But looking around at some of the docs, see below, I noticed how it's really a mix of yes/no on freeing. So I believe the (current) default of not freeing is fine, will leak some memory. As we populate this list (`string_free_me` in `wrap.jl`), we can make it a little less leaky along the way.

- CPLStrdup: pointer to a newly allocated copy of the string. Free with CPLFree() or VSIFree().
- CPLGetPath: Path in an internal string which must not be freed. The string may be destroyed by the next CPL filename handling call. The returned will generally not contain a trailing path separator.
- OGR_L_GetName: the layer name (must not been freed)

**Comment by yeesian** [comment]
I ran into something similar with https://github.com/JuliaGeo/Proj4.jl/blob/882b48a9ea75198bc3325a35a93cac36e3f1ceec/test/proj6api.jl#L11-L13 and agree with the motive of this PR, but might need a few days to properly review it (if my input is needed).

**Comment by visr** [comment]
Yeah the main reason I requested your review was not to check if I implemented my ideas correctly, Maarten could check that as well, but to make sure you are on board with this direction. If you'd like to go over it properly, that's also welcome of course, no need to rush this in.

Even if this doesn't nail it 100%, we can easily opt out of checking for errors or free more strings going forward without breaking code. To me it was a good sign that I didn't have to change any tests, just add one for the returning `nothing` for NULL strings part.

File: src/error.jl [hunk 1]
```diff
@@ -27,16 +25,62 @@ end
...
         throw(GDALError(class, errno, unsafe_string(errmsg)))
     end
     return C_NULL
 end
 
-"Throw an error if a pointer is null and GDAL reports an error"
-function failsafe(ptr)
-    if ptr == C_NULL && cplgetlasterrortype() in throw_class
+"Check the last error type and throw a GDALError if it is a failure"
+function maybe_throw()
```
Comment (evetion) [inline src/error.jl]: This function is oddly familiar to the above `gdaljl_errorhandler`. Is the above still used/needed?
The name seems too generic too, it could be something like `potential_errorhandler` or similar?

File: src/error.jl [hunk 2]
```diff
@@ -27,16 +25,62 @@ end
...
+    end
+end
+
+"""
+For string list pointers, load them to Vector{String}
+
+That is it expects a `StringList`, in the sense of the CPL functions,
+as a null-terminated array of strings.
+"""
+function aftercare(ptr::Ptr{Cstring})
```
Comment (evetion) [inline src/error.jl]: Do these pointers never need to be freed like the string pointer above?

File: src/error.jl [hunk 3]
```diff
@@ -27,16 +25,62 @@ end
...
+end
+
+"""
+Handle anything returned from GDAL
+
+When values are returned from GDAL, always check if there was a failure using `maybe_throw`.
+
+Depending on the return type, we do extra work.
+"""
+function aftercare(x)
```
Comment (evetion) [inline src/error.jl]: The naming can be more descriptive here. `gdal_errorcheck_and_free` is ugly, but more readable.

File: gen/wrap.jl [hunk 4]
```diff
@@ -136,14 +142,19 @@ function rewriter(x::Expr)
...
         end
 
-        cc2 = if rettype == :Cstring
-            :(unsafe_string($cc))
-        elseif rettype == :(Ptr{Cstring})
-            :(unsafe_loadstringlist($cc))
-        elseif isptrvoid
-            :(failsafe($cc))
+        cc2 = if occursin(r"^cpl.*error", String(f2))
+            # since we call these in aftercare, no aftercare to prevent calling itself
```
Comment (evetion) [inline gen/wrap.jl]: This feels very meta. Can it be reworded?

File: src/error.jl [hunk 5]
```diff
@@ -27,16 +25,62 @@ end
...
+end
+
+"For string pointers, load them to String, and free them if we should."
+function aftercare(ptr::Cstring, free::Bool)
+    maybe_throw()
+    if ptr == C_NULL
+        return nothing
+    else
+        s = unsafe_string(ptr)
+        free && vsifree(convert(Ptr{Cvoid}, ptr))
```
Comment (evetion) [inline src/error.jl]: Freeing memory utils could also be placed in a `memory.jl` file? `errors.jl` is just not the place I would expect them.

**Comment by evetion** [comment]
> So the new commit here effectively switches to always checking for errors, but only throwing on `CE_Failure`. I took out `CE_Fatal` from the error checking codes since this is not in need of checking anyway, if this happens, it also crashes julia, just try running `GDAL.cplemergencyerror("things are bad")` if you can lose your julia session.

This seems it's worth its own issue? From testing (on stable GDAL), it can handle one emergencyerror, but not two.

```julia
julia> using GDAL

julia> GDAL.cplemergencyerror("things are bad")
ERROR: GDALError (CE_Fatal, code 1):
	things are bad

Stacktrace:
 [1] gdaljl_errorhandler(::GDAL.CPLErr, ::Int32, ::Cstring) at /Users/me/.julia/packages/GDAL/VqKWA/src/error.jl:26
 [2] cplemergencyerror(::String) at /Users/me/.julia/packages/GDAL/VqKWA/src/cpl_error.jl:14
 [3] top-level scope at none:0

julia> GDAL.cplemergencyerror("things are bad")
FATAL: things are bad

signal (6): Abort trap: 6
in expression starting at no file:0
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 1954108 (Pool: 1953578; Big: 530); GC: 3
[1]    81882 abort      /Applications/Julia-1.1.app/Contents/Resources/julia/bin/julia
```

File: src/error.jl (hunk 1 above)
Comment (visr) [reply src/error.jl]: Hmm `maybe_throw` is not an error handler though. The `gdaljl_errorhandler` is still used. If GDAL itself throws an error, `gdaljl_errorhandler` will catch it and throw a `GDALError`. `maybe_throw` is instead used from our side, and the only thing it does is maybe throw a `GDALError` if there is a `CE_Failure`.

File: src/error.jl (hunk 2 above)
Comment (visr) [reply src/error.jl]: Yeah they do at least sometimes, see for instance:

`CPLGetConfigOptions`: a copy of the list, to be freed with `CSLDestroy()`

I didn't add it here yet since it is an improvement that we can add at any time, and because that function lives in `cpl_string.h` which we don't wrap. Which doesn't mean of course we cannot just directly ccall the function. Would be good to make an issue as a reminder though.

File: src/error.jl (hunk 3 above)
Comment (visr) [reply src/error.jl]: Yeah, though that still wouldn't describe everything it does. Then it would have to be `gdal_errorcheck_and_free_and_load_strings` ;)
And if we add a new functionality, we have to rename the function. That is why I went for the less descriptive but more general `aftercare`, since we basically do anything we need to returned values, including error checking. One benefit of this is that if we want to tweak it, we just modify the `aftercare` definitions, and don't have to run the wrapper again every time.

File: gen/wrap.jl (hunk 4 above)
Comment (visr) [reply gen/wrap.jl]: Ha what would be better? Without this you basically get StackOverflow errors, since `cplgetlasterrortype` calls `aftercare` which calls `cplgetlasterrortype` and so forth.

File: src/error.jl (hunk 5 above)
Comment (visr) [reply src/error.jl]: True that `error.jl` is not only about errors anymore. But it's less that 100 lines and I'd like to keep the `aftercare`s together. Not sure of a better name for `error.jl` though, since it's mostly that.

**Comment by visr** [comment]
> This seems it's worth its own issue? From testing (on stable GDAL), it can handle one emergencyerror, but not two.

Yeah I noticed the same thing. Though I believe it's not even supposed to be able to handle it once? See also the comment here: 
https://github.com/JuliaGeo/GDAL.jl/blob/147f62425ec08bca95091bebd4b11ca32f739a22/test/error.jl#L42-L54

Could be it's own issue, but I've never encountered a `CE_Fatal`, so it's mostly hypothetical at this point.

File: src/error.jl (hunk 2 above)
Comment (evetion) [reply src/error.jl]: Ok, we can create an issue of it. Maybe add it as a `# todo` in the code?

File: gen/wrap.jl (hunk 4 above)
Comment (evetion) [reply gen/wrap.jl]: The comments was for the comment! It just needs a small introduction for aftercare.
```julia
# We will take care of gdal error states and memory freeing (for now) by calling `aftercare`, except for `*error*` functions, as these will be called by `aftercare` itself, so we prevent a loop.
```

File: src/error.jl (hunk 1 above)
Comment (evetion) [reply src/error.jl]: Ah, handling C libraries is not easy. Would be nice to have your comment (about who throws what, calling which function) in the code here.

File: src/error.jl (hunk 2 above)
Comment (visr) [reply src/error.jl]: Yep! See 259a27c8ce78e53a078dc624cf5c3bec9a5b07f6 and #77.

File: src/error.jl (hunk 1 above)
Comment (visr) [reply src/error.jl]: 9f9a754f86c0b92f511c78ac40690b0a29390744
